#!/usr/bin/env python

import os
import json
import random
import pathlib
import argparse
import subprocess


def get_wallpaper(FOLDER):
    files = [path for path in pathlib.Path(FOLDER).iterdir()
             if path.is_file()]

    return random.choice(files)


def get_outputs():
    cmd = ['swaymsg', '-t', 'get_outputs']
    proc_result = subprocess.run(cmd, capture_output=True).stdout.decode()
    proc_json = json.loads(proc_result)

    return [output['name'] for output in proc_json]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Set a random wallpaper per output')
    parser.add_argument('folder', metavar='D', type=str, help='folder to search for images')

    args = parser.parse_args()

    cmd = 'swaylock -f'

    for output in get_outputs():
        image = get_wallpaper(args.folder)
        cmd = f'{cmd} --image {output}:{image}'

    print(cmd)
    os.system(cmd)
