#!/usr/bin/env python

import sys
import json
import time
import random
import pathlib
import argparse
import subprocess

proc = None


def get_wallpaper(FOLDER):
    files = [path for path in pathlib.Path(FOLDER).iterdir()
             if path.is_file()]

    return random.choice(files)


def get_outputs():
    cmd = ['swaymsg', '-t', 'get_outputs']
    proc_result = subprocess.run(cmd, capture_output=True).stdout.decode()
    proc_json = json.loads(proc_result)

    return [output['name'] for output in proc_json]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Set a random wallpaper per output')
    parser.add_argument('--folder', metavar='D', type=str, nargs=1,
                        help='folder to search for images')

    parser.add_argument('--delay', metavar='S', type=int,
                        help='How many seconds to wait before changing the wallpaper')

    args = parser.parse_args()

    while True:
        try:
            outputs = get_outputs()

            cmd = 'swaybg'

            for output in outputs:
                image = get_wallpaper(args.folder[0])
                cmd = f'{cmd} --image={image} --output={output}'

            print(cmd)
            proc = subprocess.Popen(cmd, shell=True)

            time.sleep(args.delay)
            proc.kill()
        except Exception as e:
            print(e, file=sys.stderr)

        finally:
            if proc:
                proc.kill()
